# This will serve as the main script 

# IMPORT DEPENDENCIES 
from treasure-items import treasure_properties
from gem-items import gem_properties, gem_combinations 


# READ IN THE TREASURE AND GEM VALUE INFORMATION 
# TREASURE ITEMS AND THEIR VALUE 
# GEM ITEMS AND THEIR VALUE 
# THE BONUS FOR THE COMBINATIONS

# DEFINE THE FUNCTION 

# GET INPUT FROM THE USER ON THEIR TREASURE ITEMS 

# GET INPUT FROM THE USER ON THEIR GEM ITEMS 

# CALCULATE AND RETURN 

# CALL THE FUNCTION 